### ISSUE TITLE
İnstagram

### ISSUE THREAD

**Issue by denizhantoy** [fastuptime/Instagram_Ac_Creator_Priv#1]
Selamlar instagram için selenium kullanmışsın bu ön planda çalışan web browser olduğundan bağlantı hızıyla sorun yaşarsın. İsimleri json dosyasında ayrı dosyadan çekmen kod okunurluğu açısından güzel olurdu. Birde unoffical apiler var oraya request ederek saniyede 10 parçacık uygulanırsa saniyede 100  tane falan açılabilir. Bunu engelleyecek tek şey ip adresinin sabit olması olur proxy kısmını inceleyeceğim proxy varsa sınırsız account mümkün. Herbirinin profil fotoğrafı ve kişisel bilgileride anında güncellenebilir.

**Comment by fastuptime** [comment]
Merhaba hocam, bu botu önceden(1-2 Yıl) yapmıştım öylesine paylaştım her hangi bir geliştirme yapmayacağım bu sebepten dolayı, ilginiz için teşekkür ederim.

**Comment by denizhantoy** [comment]
Maili attığım zamanlar githubdan indirip kullanabiliyordum sadece,şuan
kendim yazabilecek duruma geldim.Denememin sebebi el ile bile hesap
açılmıyor artık çok zorlaştı.

18 Kas 2022 Cum 18:00 tarihinde Can ***@***.***> şunu yazdı:

**Comment by fastuptime** [comment]
Tekrardan merhaba hocam, her hangi bir bilgim bulunmuyor güncel.
